spring:
  application:
    name: ${artifactId}
    version: ${version}
  jmx.enabled: true

management:
  endpoint:
    health:
      probes.enabled: true
      group:
        readiness.include: "*"
        liveness.include: livenessState,diskSpace,ping
  endpoints:
    jmx:
      exposure.include: "*"
    web:
      exposure.include: info, health

apiKey.bizEvents: ${BIZ_EVENTS_SERVICE_API_KEY:}

rest-client:
  biz-events:
    baseUrl: \${BIZ_EVENTS_BASE_URL:}