package it.gov.pagopa.arc.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class ArcErrorDTO {
    /**
     * This DTO is temporary and will be eliminated,
     * as it will be replaced by the one generated by openapiGenerator,
     * it reflects the structure that the one generated will have.
     */
    public enum ErrorEnum {
        INVALID_REQUEST("invalid_request"),
        UNAUTHORIZED("unauthorized"),
        TOO_MANY_REQUEST("too_many_request"),
        INTERNAL_SERVER_ERROR("internal_server_error");

        private final String value;

        ErrorEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static ErrorEnum fromValue(String value) {
            for (ErrorEnum b : ErrorEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

    }

    private ErrorEnum error;

    @com.fasterxml.jackson.annotation.JsonProperty("error_description")
    private String errorDescription;

}
