name: 📦 Payments Snapshot docker

on:
  push:
    branches-ignore:
      - 'develop'
      - 'uat'
      - 'main'
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'
  workflow_dispatch:

env:
  CURRENT_BRANCH: ${{ github.event.inputs.branch || github.ref_name }}

jobs:
  payments-flow-docker-snapshot:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: 🔖 Checkout code
        # https://github.com/actions/checkout/releases/tag/v4.2.1
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          ref: ${{ env.CURRENT_BRANCH }}

      - name: 📦 Run Snapshot Docker Build/Push & Trigger
        # https://github.com/pagopa/github-actions-template/releases/tag/v1.19.2
        uses: pagopa/github-actions-template/payments-flow-docker-snapshot@922ed4e43b0e45a5e47eb0296d550996d8c87c64
        with:
          current_branch: ${{ github.ref_name }}
          enable_azure_devops_step: 'true'
          azure_devops_project_url: 'https://dev.azure.com/pagopaspa/arc-projects'
          azure_devops_pipeline_name: 'arc-cittadini-deploy-aks.deploy'
          azure_devops_pat: ${{ secrets.AZUREDEVOPS_PAT }}
          azure_template_parameters: |
            {
              "APPS": "[arb-be]",
              "POSTMAN_BRANCH": "${{ github.ref_name }}"
            }
